In [1]:
import pandas as pd

# Data Loading

In [2]:
df=pd.read_csv("india_climate_2000_2025.csv")

# Data Information Gathering

In [3]:
df.shape

(3120, 16)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3120 entries, 0 to 3119
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            3120 non-null   int64
 1   month           3120 non-null   int64
 2   season          3120 non-null   object
 3   state           3120 non-null   object
 4   region          3120 non-null   object
 5   avg_temp_c      3120 non-null   float64
 6   max_temp_c      3120 non-null   float64
 7   min_temp_c      3120 non-null   float64
 8   rainfall_mm     3120 non-null   float64
 9   humidity_pct    3120 non-null   float64
 10  wind_speed_kmh  3120 non-null   float64
 11  sunshine_hrs    3120 non-null   float64
 12  heat_index      3120 non-null   float64
 13  temp_anomaly_c  3120 non-null   float64
 14  el_nino_flag    3120 non-null   int64
 15  drought_flag    3120 non-null   int64
dtypes: float64(9), int64(4), object(3)
memory usage: 390.1+ KB

In [5]:
df.head()

,year,month,season,state,region,avg_temp_c,max_temp_c,min_temp_c,rainfall_mm,humidity_pct,wind_speed_kmh,sunshine_hrs,heat_index,temp_anomaly_c,el_nino_flag,drought_flag
0,2000,1,Winter,Assam,Northeast,16.15,26.38,8.55,0.40,61.40,1.51,3.70,26.87,0.06,0,0
1,2000,2,Winter,Assam,Northeast,16.89,28.49,7.90,0.26,55.09,1.76,4.72,26.79,-2.02,0,1
2,2000,3,Summer,Assam,Northeast,22.57,36.37,11.70,0.89,52.35,1.80,4.59,24.94,-0.99,0,1
3,2000,4,Summer,Assam,Northeast,27.17,36.63,16.71,4.44,61.14,1.80,5.05,28.39,0.44,0,0
4,2000,5,Summer,Assam,Northeast,28.26,40.23,21.12,6.80,70.88,1.55,4.84,31.31,0.25,0,0

In [6]:
df.tail()

,year,month,season,state,region,avg_temp_c,max_temp_c,min_temp_c,rainfall_mm,humidity_pct,wind_speed_kmh,sunshine_hrs,heat_index,temp_anomaly_c,el_nino_flag,drought_flag
3115,2025,8,Monsoon,West Bengal,East,28.06,32.68,24.90,8.74,90.00,8.14,3.88,33.94,-0.15,0,0
3116,2025,9,Monsoon,West Bengal,East,27.93,32.37,24.13,6.54,89.23,5.65,4.42,33.40,0.47,0,0
3117,2025,10,Post-Monsoon,West Bengal,East,26.40,31.81,19.04,4.70,85.65,5.00,4.33,28.80,0.70,0,0
3118,2025,11,Post-Monsoon,West Bengal,East,20.32,30.46,11.91,0.08,81.52,5.54,4.15,20.91,-1.43,0,1
3119,2025,12,Winter,West Bengal,East,15.70,24.36,6.93,0.00,81.87,5.80,3.32,22.09,-1.67,0,1

In [7]:
df.min()

year                 2000
month                   1
season            Monsoon
state               Assam
region            Central
avg_temp_c          10.82
max_temp_c           21.1
min_temp_c          -0.97
rainfall_mm           0.0
humidity_pct        12.39
wind_speed_kmh       0.97
sunshine_hrs         1.82
heat_index           20.4
temp_anomaly_c      -4.94
el_nino_flag            0
drought_flag            0
dtype: object

In [8]:
df.max()

year                     2025
month                      12
season                 Winter
state             West Bengal
region                   West
avg_temp_c              38.07
max_temp_c              49.99
min_temp_c              28.54
rainfall_mm              28.2
humidity_pct            93.05
wind_speed_kmh          20.45
sunshine_hrs             7.63
heat_index              42.13
temp_anomaly_c           4.71
el_nino_flag                1
drought_flag                1
dtype: object

In [9]:
df.count()

year              3120
month             3120
season            3120
state             3120
region            3120
avg_temp_c        3120
max_temp_c        3120
min_temp_c        3120
rainfall_mm       3120
humidity_pct      3120
wind_speed_kmh    3120
sunshine_hrs      3120
heat_index        3120
temp_anomaly_c    3120
el_nino_flag      3120
drought_flag      3120
dtype: int64

In [10]:
df.describe()

,year,month,avg_temp_c,max_temp_c,min_temp_c,rainfall_mm,humidity_pct,wind_speed_kmh,sunshine_hrs,heat_index,temp_anomaly_c,el_nino_flag,drought_flag
count,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000
mean,2012.500000,6.500000,25.855446,35.585010,17.249737,3.069324,60.638458,7.075333,5.046141,28.795670,-0.078388,0.269231,0.396795
std,7.501202,3.452606,5.040327,5.525251,6.434247,3.971285,21.415260,3.533179,1.046125,4.433421,1.078195,0.443631,0.489311
min,2000.000000,1.000000,10.820000,21.100000,-0.970000,0.000000,12.390000,0.970000,1.820000,20.400000,-4.940000,0.000000,0.000000
25%,2006.000000,3.750000,22.875000,31.377500,12.137500,0.150000,43.335000,4.970000,4.290000,25.010000,-0.680000,0.000000,0.000000
50%,2012.500000,6.500000,26.410000,34.870000,18.940000,1.220000,63.585000,6.520000,4.910000,27.850000,0.000000,0.000000,0.000000
75%,2019.000000,9.250000,29.050000,39.710000,22.675000,4.842500,79.505000,8.820000,5.760000,32.132500,0.560000,1.000000,1.000000
max,2025.000000,12.000000,38.070000,49.990000,28.540000,28.200000,93.050000,20.450000,7.630000,42.130000,4.710000,1.000000,1.000000

# Data Cleaning

In [11]:
# handling Null values
df.isnull().sum()
# No null values, so no changes required

year              0
month             0
season            0
state             0
region            0
avg_temp_c        0
max_temp_c        0
min_temp_c        0
rainfall_mm       0
humidity_pct      0
wind_speed_kmh    0
sunshine_hrs      0
heat_index        0
temp_anomaly_c    0
el_nino_flag      0
drought_flag      0
dtype: int64

In [12]:
# removing Unwanted column
# Removing month as month can be identified via monsoon cycle or season in this case
df.drop(columns=['month','region'],inplace=True)

In [13]:
df.head(2)

,year,season,state,avg_temp_c,max_temp_c,min_temp_c,rainfall_mm,humidity_pct,wind_speed_kmh,sunshine_hrs,heat_index,temp_anomaly_c,el_nino_flag,drought_flag
0,2000,Winter,Assam,16.15,26.38,8.55,0.40,61.40,1.51,3.70,26.87,0.06,0,0
1,2000,Winter,Assam,16.89,28.49,7.90,0.26,55.09,1.76,4.72,26.79,-2.02,0,1

In [14]:
# removing Duplicate rows
df.duplicated().sum()
# No duplicates so no removing

np.int64(0)

In [15]:
# Renaming necessary columns
df.rename(columns={'rainfall_mm':'rainfall_index'},inplace=True)
df.head()

,year,season,state,avg_temp_c,max_temp_c,min_temp_c,rainfall_index,humidity_pct,wind_speed_kmh,sunshine_hrs,heat_index,temp_anomaly_c,el_nino_flag,drought_flag
0,2000,Winter,Assam,16.15,26.38,8.55,0.40,61.40,1.51,3.70,26.87,0.06,0,0
1,2000,Winter,Assam,16.89,28.49,7.90,0.26,55.09,1.76,4.72,26.79,-2.02,0,1
2,2000,Summer,Assam,22.57,36.37,11.70,0.89,52.35,1.80,4.59,24.94,-0.99,0,1
3,2000,Summer,Assam,27.17,36.63,16.71,4.44,61.14,1.80,5.05,28.39,0.44,0,0
4,2000,Summer,Assam,28.26,40.23,21.12,6.80,70.88,1.55,4.84,31.31,0.25,0,0